### ISSUE TITLE
Use OpenZeppelin eternal storage contracts as dependency

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#324]
As part of the security audit the following finding was raised:

**Description**: The clone-and-own approach involves copying and adjusting open source code at one's own discretion. From the development perspective, it is initially beneficial as it reduces the amount of effort. However, from the security perspective, it involves some risks as the code may not follow the best practices, may contain a security vulnerability, or may include intentionally or unintentionally modified upstream libraries. Rather than the clone- and-own approach, a good industry practice is to use the Truffle framework for managing library dependencies. This eliminates the clone-and-own risks yet allows for following best practices, such as, using libraries.

**Recommendation**: Since upgradeability clones most of the behavior in `https://github.com/OpenZeppelin/openzeppelin- labs/tree/master/upgradeability_using_eternal_storage`, we recommend using the latter as a dependency, rather than cloning its code.

Since the tokenbridge contracts are using a customised version of the sources mentioned above, research and implement a way how to use the original code as dependency for the bridge.

**Comment by k1rill-fedoseev** [comment]
Hi, @patitonar, I have some troubles with implementing this.
I am trying to use `openzeppelin-labs` repository as a dependency. 
So far, in f86e876673296b8248a7aae3788e52030636f3a1, I have added the dependency and changed import paths in Solidity contracts. But for some reason, `npm run coverage` is [failing](https://travis-ci.org/poanetwork/tokenbridge-contracts/builds/623134536) and throwing some sort of Compilation error.
```
error OwnedUpgradeabilityProxy.sol:3:1: ParserError: Source "/Users/kirillfedoseev/work/tokenbridge-contracts/node_modules/openzeppelin-labs/upgradeability_using_eternal_storage/contracts/UpgradeabilityProxy.sol" not found: File import callback not supported
import './UpgradeabilityProxy.sol';
^---------------------------------^

error OwnedUpgradeabilityProxy.sol:4:1: ParserError: Source "/Users/kirillfedoseev/work/tokenbridge-contracts/node_modules/openzeppelin-labs/upgradeability_using_eternal_storage/contracts/UpgradeabilityOwnerStorage.sol" not found: File import callback not supported
import './UpgradeabilityOwnerStorage.sol';
^----------------------------------------^
```
Maybe you can give me a little help with this one?

**Comment by patitonar** [comment]
Hi @k1rill-fedoseev! 

It looks like it is an error from `@0x/sol-compiler` which is used to internally compile the contracts to be used by coverage tool `@0x/sol-coverage`. I found this issue which describes a similar case https://github.com/0xProject/0x-monorepo/issues/2094

It doesn't look like a fix will be provided. After trying a couple of options, I found the following workaround to work:
1. Update 0x dependencies:
`npm i --save @0x/sol-coverage@latest @0x/sol-trace@latest @0x/subproviders@latest`
2. Create a new test contract, for example `contracts/mocks/LabsMocks.sol`:
```solidity
pragma solidity 0.4.24;

import "openzeppelin-labs/upgradeability_using_eternal_storage/contracts/UpgradeabilityOwnerStorage.sol";
import "openzeppelin-labs/upgradeability_using_eternal_storage/contracts/UpgradeabilityProxy.sol";
import "openzeppelin-labs/upgradeability_using_eternal_storage/contracts/Proxy.sol";
import "openzeppelin-labs/upgradeability_using_eternal_storage/contracts/UpgradeabilityStorage.sol";

/**
 * @title LabsMocks
 * @dev This contract is not used at all. It is just to workaround an issue with imported dependencies by 0x-sol-compiler
 * used in the test coverage report tool.
 */
// solhint-disable-next-line no-empty-blocks
contract LabsMocks is UpgradeabilityOwnerStorage, Proxy, UpgradeabilityStorage, UpgradeabilityProxy {}
```

The issue seems to be with the indirect contract dependencies, so having all imports in a direct way helps to properly load the files. It is not the best solution but it was the only way I was able to make it work.

We are using `0x` tools because `solidity-coverage` was not working with our truffle and solidity version (see details here https://github.com/poanetwork/tokenbridge-contracts/pull/191#issue-288464063). If we upgrade our contracts in the future to a newer solidity version we should consider switching back to `solidity-coverage`
