### ISSUE TITLE
Support metatransactions using GSN & ERC-2612 permit

### ISSUE THREAD

**Issue by dmihal** [poanetwork/tokenbridge-contracts#450]
Currently, bridged tokens still require gas to be paid in the native asset (xDai) for transfers or other transactions. This limits the usability of these tokens and means some users may have their tokens "stuck".

The ERC677BridgeToken contract should add support for Gas Station Network as well as ERC-2612 permit functions. This will give developers the flexibility to pay gas costs on behalf of users.

**Comment by akolotov** [comment]
We already have support of the `permit` function for the bridgeable token:

https://github.com/poanetwork/tokenbridge-contracts/blob/master/contracts/PermittableToken.sol

And an adopter could modify slightly the deployment scripts to deploy the Permittable token instead of the vanilla ERC677-based token. Is it enough for supporting GSN?
