### ISSUE TITLE
Docker deployment of AMB contracts fails in version 5.0.0+

### ISSUE THREAD

**Issue by olivdb** [poanetwork/tokenbridge-contracts#554]
Docker deployment of the bridge contracts in `ARBITRARY_MESSAGE` mode fails in all versions following 5.0.0:

```
docker run -it --env-file amb.config poanetwork/tokenbridge-contracts:5.5.0 deploy.sh
```

```
...
initializing Home Bridge with following parameters:

SOURCE_CHAIN_ID: 1337, DESTINATION_CHAIN_ID: 1337, Home Validators: 0x393A6a6850e0788e496d73c50a436606e6CcA874,
  HOME_MAX_AMOUNT_PER_TX (gas limit per call): 20000000,
  HOME_GAS_PRICE: 1000000000, HOME_REQUIRED_BLOCK_CONFIRMATIONS : 1
  
Error: web3 RPC failed: {"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"0xbdff8cdd478a777d1576a7b7de4262dff6bda108c8e773ce90d5bc5f9fb9ba32":{"error":"revert","program_counter":194,"return":"0x"},"stack":"o: VM Exception while processing transaction: revert\n    at Function.o.fromResults (/Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:89727)\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:121891\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:98434\n    at p (/Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:98092)\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:98145\n    at t.default (/Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:544303)\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:99058\n    at t.n.emit (/Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:16355)\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:654328\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:654351\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:1093609\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:19209\n    at i (/Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:34308)\n    at /Users/oli/ethereum/tokenbridge-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:14717\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","name":"o"}}
    at sendNodeRequest (/contracts/deploy/src/deploymentUtils.js:161:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: TypeError: Cannot read property 'status' of undefined
    at initializeBridge (/contracts/deploy/src/arbitrary_message/home.js:64:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The same deployment succeeds in version 4.1.1:
```
docker run -it --env-file amb.config poanetwork/tokenbridge-contracts:4.1.1 deploy.sh
```
```
...
Contracts Deployment have been saved to `bridgeDeploymentResults.json`
{
    "homeBridge": {
        "address": "0xdC78afe9cFDe0576Ff236667DC8c380615c24Ca9",
        "deployedBlockNumber": 80
    },
    "foreignBridge": {
        "address": "0xE8e43b5D61C43375aB7b651F1419F2a81C5E6615",
        "deployedBlockNumber": 90
    }
}
```

I built the `amb.config` from the [provided template](https://github.com/poanetwork/tokenbridge-contracts/tree/master/deploy#arbitrary-message-bridge-mode-configuration-example), providing the same EOA for all owners/admins/single validator, and using the same RPC endpoint for both the home and foreign environments. I obtained the same results using https://sokol.poa.network and http://host.docker.internal:8545 (local ganache) as RPC URLs.

**Comment by k1rill-fedoseev** [comment]
Thanks for pointing this out!

The problem in your case lies in the fact of using the same network for both, home and foreign chains. It appears in the `5.0.0+` versions only, since the latest major version of AMB contract introduced the work with chain ids inside the contracts. Our AMB contracts have the following check that does not allow the use of the same network for both sides of the bridge: https://github.com/poanetwork/tokenbridge-contracts/blob/835742dfd8f1c869d4e7b61582155d250d6cf094/contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol#L108

Unfortunately, chain ids were not checked before the deployment started. I will open a PR and add such pre-flight check.

Also, can you please provide us a little more details about the use case you are trying to achieve by using the same network on both sides of the bridge. This will help us to find the best way out for your particular problem.

**Comment by olivdb** [comment]
Thanks @k1rill-fedoseev, that makes sense.

The use case would be to be able to run end-to-end tests of the mediators using a single ganache instance instead of two.

**Comment by k1rill-fedoseev** [comment]
I would suggest you to try using two separate ganache instances for your e2e tests if possible, since other bridge components are not intended to be used within the single chain either. For instance, oracles which are responsible for sending transactions to the Arbitrary Message Bridge contracts have different workers for submitting transactions to Home and Foreign chains, using the same chain and RPC URL for both of them may lead to unexpected nonce overlapping or other problems.
